workspace 'liukaiCaseWorkspace'
#配置依赖第三方库的程程
#配置工程中包含POD的target
 xcodeproj './photoBrowser/photoBrowser.xcodeproj' 
target 'photoBrowser' do
 xcodeproj './photoBrowser/photoBrowser.xcodeproj' 
 platform:ios, '7.0'
 pod 'CXPhotoBrowser', '~> 1.1.1' 
#pod 'libarary', path=> ''
end
target 'NewsApp' do
 xcodeproj './NewsApp/NewsApp.xcodeproj' 
 platform:ios, '7.0'
 pod 'CocoaAsyncSocket', '~> 7.3.5'
 pod "CocoaLumberjack","~>1.9.1"
 pod "ASIHTTPRequest", "~> 1.8.2"
 pod "SDWebImage", "~> 3.7.0"
 pod 'GDataXML-HTML', '~> 1.1.0'
 pod 'MSDynamicsDrawerViewController', '~> 1.5.1' 
end
